An array is a grid of values and it contains information about the raw data, 
how to locate an element, and how to interpret an element. 

It has a grid of elements that can be indexed in various ways. The elements 
are all of the same type, referred to as the array **`dtype`**.

An array can be indexed by a tuple of nonnegative integers, by booleans, 
by another array, or by integers.

The **`rank`** of the array is the number of dimensions.

The **`shape`** of the array is a tuple of integers giving the size of the 
array along each dimension.

# Difference between Python list and NumPy array

A Python list can contain different data types within a single list, all of
the elements in a NumPy array should be homogeneous.

The mathematical operations that are meant to be performed on arrays would
be extremely inefficient if the arrays weren't homogeneous.

# Initialize Numpy array

The NumPy **`ndarray`** class is used to represent both matrices and vectors.

A **vector** is an array with a single dimension (there's no difference
 between row and column vectors).

A **matrix** refers to an array with two dimensions.

For **3-D** or higher dimensional array, the tern **tensor** is also commonly used

An array is usually a fixed-size container of items of the same type and size.

In NumPy, dimensions are called **axes**. For example:

```
[[0., 0., 0.],
 [1., 1., 1.]]
```

The array has 2 axes. The first axis has a length of 2 and the second axis
has a length of 3.

The contents of an array can be accessed and modified by indexing or slicing
the array.

# Create arrays

## Convert Python sequences to NumPy array

NumPy arrays can be defined using Python sequences such as lists and tuples.

In general, any array object is called an **`ndarray`** in NumPy.

When using **`numpy.array()`** to define a new array, you should consider the 
[dtype](https://numpy.org/doc/stable/user/basics.types.html) of the elements 
in array, which can be specified explicitly. This feature gives you more control 
over the underlying data structures and how the elements are handled in `C/C++` 
functions. 

When you perform operations with different **`dtype`**, NumPy will assign a new 
type that satisfies all of the array elements involved in the computation.

The default NumPy behavior is to create arrays either 64-bits signed integers or 
double precision floating point numbers, **`int64`** and **`float`**, respectively. 
If you expect your array to be a certain type, then you need to specify the 
**`dtype`** while you create the arrary.

## Intrinsic NumPy array creation functions

NumPy has over 40 built-in functions for creating arrays as laid out in the 
[Arrary creation routines](https://numpy.org/doc/stable/reference/routines.array-creation.html#routines-array-creation). 
These functions can be split into roughly three categories, based on the 
dimension of the array they create.

### 1D arrays

### 2D arrays

### General ndarrays

## Replacating, joining, or mutating existing arrays

+ Create a new array from a section of array by using **slice** and **stride**.

+ Stack two existing arrays
  + **`np.vstack`**, stack two array vertically
  + **`np.hstack()`**, stack two array horizontally

+ Split existing array

  Split an array into several smaller arrays.

+ **`view()`**

+ **`copy()`**

  Make a complete copy of the original array. Deep copy.

## Reading arrays from disk, either from standard or custom formats

[Reading and writing files](https://numpy.org/doc/stable/user/how-to-io.html#how-to-io)

### Standard Binary Formats

### Common ASCII Formats

More generic ASCII files can be read using **`scipy.io`** and **`Pandas`**.

## Creating arrays from raw bytes through the use of strings or buffers

## Use of special library functions

+ SciPy

+ Pandas

+ OpenCV

# Shape and size of an array

+ **`ndarray.ndim`**

Return the number of axes, or dimensions, of an array.

+ **`ndarray.size`**

Return the total number of elements of the array. This is the product of 
elements of the array's shape.

+ **`ndarray.shape`**

Return a tuple of integers that indicate the number of elements stored along
each dimension of a array. For example, a 2-D array with **2 rows** and **3 columns**, 
the shape of the array is **`(2, 3)`**.

## Reshap an array

**`arr.reshap()`**

Return a nes shape to an array without changing the data. Remember that when 
using the reshap method, the array you want to produce needs to have the 
same number of elements as the original array.

# Convert a 1D array into a 2D array

+ **`np.newaxis`**

Increase the dimensions of your array by one dimension when used once.

+ **`np.expand_dims`**

Expand an array by increasing a nes axis at a specified position.

```np.expand_dims(a, axis=1)```

# Indexing and slicing

## Single element indexing

### 1-D array

Single element indexing for a 1-D array os what one expects. It works exactly 
like that for other standard Python sequences. It is 0-based, and accepts 
negative indices for indexing from the end of the array.

### Multidimensional array

NumPy arrays support **multidimensional indexing** for multidimensional arrays.

In [16]:
import numpy as np

data = np.arange(12).reshape(4, 3)

print(data)
print(data[1])
print(data[1, 2])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[3 4 5]
5


Note that if one indexes a multidimensional array with fewer indices than 
dimensions, one gets a subdimensional array. That is, each index specified 
selects the array corresponding to the rest of the dimensions selected.

Note that the returned array is not a copy of the original, but 
points to the same values in memory as does the original array.

NumPy uses C-order indexing. That menas that the last index 
usually represents the most rapidly changing memory location.

## Slice and stride

Slicing and strading works exactly the same way it does 
for lists and tuples except that they can be applied to 
multiple dimensions.

In [17]:
import numpy as np

data = np.arange(35).reshape(5, 7)

print(data)
print(data[1:5:2, ::3])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]
[[ 7 10 13]
 [21 24 27]]


Note that slices of arrays do not copy the internal array data 
but only produce new views of the original data. 

Explicit **`copy()`** is recommended if the original data 
is not required anymore.

## Index arrays

NumPy arrays may be indexed with other arrays (or any sequence-like object 
that can be convert to an array, such as lists, with the exception of
tuples).

Index arryas must be of integer type. Each value in the array indicates 
which value in the array to use in place of the index.

In [2]:
import numpy as np

data = np.arange(10, 1, -1)

data[np.array([3, 3, -3, 8])]

array([7, 7, 4, 2])

## Index multi-dimensional arrays

## Boolean or "mask" index arrays

Boolean arrays must be of the same shape as the initial dimensions 
of the array being indexed. In the most straightforward case, 
the boolean array has the same shape.

In general, when the boolean array has fewer dimensions than the 
array being indexed, the shape of the result is one dimension 
containing the number of **True** elements of the boolean array. 

As show in the following example, using a 2-D boolean arrary of 
shape (2, 3) with four True elements to select rows from a 
3-D array of shape (2, 3, 5) results in a 2-D result of 
shape (4, 5)

In [10]:
import numpy as np

data = np.arange(30).reshape(2, 3, 5)

print(data)

b = np.array([[True, True, False], [False, True, True]])
data[b]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

## Combine index arrays with slices

## Structural indexing tools

### Ellipsis

Ellipsis (**`...`***) expands to the number of **`:`** objects 
needed for the selection tuple to index all dimensions. There 
may only be a single ellipsis present.

newaxis

## Assign values to indexed arrays

## Dealing with variable numbers of indices within programs

# Array operations

## Arithmetical operations

The two array should have the same columns.

+ **`+`**

+ **`-`**

+ **`*`**

+ **`/`**

## Aggregation functions


+ **`data.sum()`**, return sum of the elements in an array.

+ **`data.min()`**, return the minimum element in an array.
 
+ **`data.max()`**, return the maximum element in an array.

+ **`data.mean()`**

+ **`data.prod()`**

## Broadcasting

**Broadcasting** describes how NumPy treates arrays with different shapes during 
arithmetic operations.

### General Brocadcasting Rules

When operating on two arrays, NumPy compares their shapes element-wise. It starts 
with the trailing (i.e. rightmost) dimensions and works its way left. The two 
dimensions are compatible when

 1. they are equal, or
 2. one of them is 1

If these conditions are not met, a `ValueError: operands could not be broadcast together` 
exception is thrown, indicating the arrays have incompatible shapes. 

The size of the resulting array is the size that is not 1 along each axis of the inputs.

Arrays do not need to have the same *number* of dimensions. For examples, if you have
a `256x256x3` array of RGB values, and you want to scale each color in the image by 
different value, you can multiply the image by a one-dimension array with 3 values.

Broadcasting provides a convenient way of taking the **outer product** of two arrays.